name: face_distance_app
description: "A Flutter project to display face distance detected by a Python server."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  audioplayers: ^4.0.1 # Ensure you have a version compatible with Dart 2.19
  cupertino_icons: ^1.0.5
  camera: ^0.10.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/beepbeepbeep-53921.mp3
